# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
        	| sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
	        && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
	        | sudo tee /etc/apt/sources.list.d/ngrok.list \
	        && sudo apt update \
	        && sudo apt install ngrok
    - name: Auth

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: ssh start
      run: sudo systemctl start ssh
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Create Tunnel
        run: .\ngrok\ngrok.exe tcp 3389
