# This is a basic workflow to help you get started with Actions

name: CI3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install
        run:  |
          wget -P /home/runner/Downloads https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          ls /home/runner/Downloads/
      - name: extract
        run: | 
          sudo tar -xvzf ~/Downloads/ngrok-v3-stable-linux-amd64.tgz -C /home/runner/Downloads
          ls /home/runner/Downloads/

      - name: Auth
        run: |
          cd /home/runner/Downloads
          ./ngrok config add-authtoken 2p7aKNhdmC6GxOyW7u7hkRRsCgE_59JeGwT3qMwx7cnSQQmZy
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: tunnel
        run: |
           docker run -p 6080:80 -v /dev/shm:/dev/shm dorowu/ubuntu-desktop-lxde-vnc
           cd /home/runner/Downloads
           ./ngrok tcp 6080


